name: 'AXEFIELD '
favicon: null
layout_spectrum: 0.4661477683112025
typography_spectrum: 0.6142471602652222
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6cbe45'
    - '#f5eb22'
    - '#f58141'
    - '#000000'
    - '#00ff00'
  brandStrength: 0.625
  lightness: 0.4222203262615949
  saturation: 0.7123201151844114
  rhythmicContrast: 0.07972649880684912
purpose: []
